/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresselRouteImport } from './routes/pressel'
import { Route as Obrigado4RouteImport } from './routes/obrigado4'
import { Route as Obrigado3RouteImport } from './routes/obrigado3'
import { Route as Obrigado2RouteImport } from './routes/obrigado2'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BackRedirectRouteImport } from './routes/back-redirect'
import { Route as IndexRouteImport } from './routes/index'

const PresselRoute = PresselRouteImport.update({
  id: '/pressel',
  path: '/pressel',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado4Route = Obrigado4RouteImport.update({
  id: '/obrigado4',
  path: '/obrigado4',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado3Route = Obrigado3RouteImport.update({
  id: '/obrigado3',
  path: '/obrigado3',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado2Route = Obrigado2RouteImport.update({
  id: '/obrigado2',
  path: '/obrigado2',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BackRedirectRoute = BackRedirectRouteImport.update({
  id: '/back-redirect',
  path: '/back-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/back-redirect'
    | '/checkout'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/back-redirect'
    | '/checkout'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
  id:
    | '__root__'
    | '/'
    | '/back-redirect'
    | '/checkout'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackRedirectRoute: typeof BackRedirectRoute
  CheckoutRoute: typeof CheckoutRoute
  ObrigadoRoute: typeof ObrigadoRoute
  Obrigado2Route: typeof Obrigado2Route
  Obrigado3Route: typeof Obrigado3Route
  Obrigado4Route: typeof Obrigado4Route
  PresselRoute: typeof PresselRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pressel': {
      id: '/pressel'
      path: '/pressel'
      fullPath: '/pressel'
      preLoaderRoute: typeof PresselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado4': {
      id: '/obrigado4'
      path: '/obrigado4'
      fullPath: '/obrigado4'
      preLoaderRoute: typeof Obrigado4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado3': {
      id: '/obrigado3'
      path: '/obrigado3'
      fullPath: '/obrigado3'
      preLoaderRoute: typeof Obrigado3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado2': {
      id: '/obrigado2'
      path: '/obrigado2'
      fullPath: '/obrigado2'
      preLoaderRoute: typeof Obrigado2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-redirect': {
      id: '/back-redirect'
      path: '/back-redirect'
      fullPath: '/back-redirect'
      preLoaderRoute: typeof BackRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackRedirectRoute: BackRedirectRoute,
  CheckoutRoute: CheckoutRoute,
  ObrigadoRoute: ObrigadoRoute,
  Obrigado2Route: Obrigado2Route,
  Obrigado3Route: Obrigado3Route,
  Obrigado4Route: Obrigado4Route,
  PresselRoute: PresselRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
